In [8]:
import numpy as np



In [5]:
# ch 2 exercises

#  CREATE A NP ARRAY - 1 dimensional , 10 elements , all initialized to zero

array = np.zeros(10)


In [6]:
array


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# reshape the array into a 2 x 5 matrix

array.reshape(2,5) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# ELEMENT WISE ADDITION AND MULTIPLICATION
# create matrix a and b of size 3 x 3 perform element wise addition and multiplication 

A = np.random.rand(3,3)
B = np.random.rand(3,3)

sum_matrix = A + B


mult_matrix = A * B

In [12]:
sum_matrix

array([[0.96084614, 1.2802071 , 0.77832297],
       [0.93475676, 0.2226236 , 0.42003483],
       [1.56951766, 0.39186828, 1.06956356]])

In [13]:
mult_matrix

array([[0.08218098, 0.39628187, 0.14616014],
       [0.20708517, 0.0034256 , 0.032831  ],
       [0.58873533, 0.00320187, 0.26508655]])

In [14]:
A

array([[0.09490349, 0.75608065, 0.31645302],
       [0.36080735, 0.0166296 , 0.10382743],
       [0.9494133 , 0.38351964, 0.6793674 ]])

In [15]:
B

array([[0.86594265, 0.52412645, 0.46186995],
       [0.57394941, 0.205994  , 0.3162074 ],
       [0.62010436, 0.00834864, 0.39019616]])

In [16]:
# transpose matrix A
transposed_A = A.T

transposed_A

array([[0.09490349, 0.36080735, 0.9494133 ],
       [0.75608065, 0.0166296 , 0.38351964],
       [0.31645302, 0.10382743, 0.6793674 ]])

In [17]:
# multiply matrices a and b using matrix multiplication

dot_product = np.dot(A,B)
dot_product

array([[0.71236692, 0.20813146, 0.40639012],
       [0.38636687, 0.19340109, 0.21241754],
       [1.46353703, 0.58228716, 0.82486378]])

In [18]:
# get the diagonal elements
dot_product.diagonal()

array([0.71236692, 0.19340109, 0.82486378])